{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.namespace.name }}-crb
  namespace: {{ .Values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole 
  name: {{ .Values.namespace.name }}-cr
subjects:
  - kind: ServiceAccount
    name: {{ .Values.namespace.name }}-sa
    namespace: {{ .Values.namespace.name }}
{{- end }}
