{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.namespace.name }}-sa
  namespace: {{ .Values.namespace.name }}
  {{ if eq .Values.serviceAccount.provider "aws" }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.serviceAccount.arn }}"
  {{ else if eq .Values.serviceAccount.provider "gcp" }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.serviceAccount.gcp_service_account_name }}@{{ .Values.serviceAccount.project_id }}.iam.gserviceaccount.com"
  {{ end }}
  labels:
    {{- include "K2ViewAgent.labels" . | nindent 4 }}
{{- end }}
